language: python
python:
  - "3.8"
# command to install dependencies
install:
  - pip install flake8
  - pip install pep257
# command to run tests
script:
  - flake8 . --max-line-length=120
  - pep257 . --add-ignore=D202
